# Generated by Django 5.2.3 on 2025-08-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desk_number', models.IntegerField()),
            ],
            options={
                'db_table': 'tsd_desks',
                'managed': False,
            },
        ),
    ]
