# Generated by Django 5.2.3 on 2025-08-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_desks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shifts',
        ),
        migrations.DeleteModel(
            name='ShiftTemplates',
        ),
        migrations.DeleteModel(
            name='ShiftTypes',
        ),
    ]
