# Generated by Django 5.2.3 on 2025-08-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_date', models.DateField()),
                ('job_title', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lunch_start_time', models.TimeField()),
                ('lunch_end_time', models.TimeField()),
                ('work_hours', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'tsd_shifts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_fixed_time', models.BooleanField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lunch_start_time', models.TimeField()),
                ('lunch_end_time', models.TimeField()),
                ('icon', models.CharField(max_length=50)),
                ('allowed_roles', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'tsd_shift_templates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=1)),
                ('is_work_shift', models.BooleanField()),
            ],
            options={
                'db_table': 'tsd_shift_types',
                'managed': False,
            },
        ),
    ]
