# Generated by Django 5.2.3 on 2025-09-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_shifts_delete_shifttemplates_and_more'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarAnomalies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tsd_calendar_anomalies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarAnomalyTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tsd_calendar_anomaly_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shifts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
