"""
Django settings for TSDPortal project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Загружаем .env из корня проекта (рядом с manage.py)
dotenv_path = os.path.join(BASE_DIR, '.env')
if os.path.exists(dotenv_path):
    load_dotenv(dotenv_path)
    print(f"✓ Loaded .env from: {dotenv_path}")
else:
    print(f"⚠ WARNING: .env file not found at {dotenv_path}")
    print(f"  Current working directory: {os.getcwd()}")
    print(f"  Using environment variables from system")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-*sg=10h4j21_k(@j3615jwyv$#z$zet$@56-gcar+gq5)377yw')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',
    'drf_spectacular',
    'drf_yasg',
    'users',
    'shifts',
    'corsheaders',
    'mozilla_django_oidc',
]

OIDC_RP_CLIENT_ID = os.getenv('OIDC_CLIENT_ID')
OIDC_RP_CLIENT_SECRET = os.getenv('OIDC_CLIENT_SECRET')
OIDC_OP_AUTHORIZATION_ENDPOINT = os.getenv('OIDC_AUTH_ENDPOINT')
OIDC_OP_TOKEN_ENDPOINT = os.getenv('OIDC_TOKEN_ENDPOINT')
OIDC_OP_USER_ENDPOINT = os.getenv('OIDC_USERINFO_ENDPOINT')
OIDC_OP_JWKS_ENDPOINT = os.getenv('OIDC_JWKS_ENDPOINT')
OIDC_OP_LOGOUT_ENDPOINT = os.getenv('OIDC_LOGOUT_ENDPOINT')

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/oidc/authenticate/'

# Callback URL, зарегистрированный в ADFS — backend принимает code здесь
# Значение берём из .env; fallback для локальной разработки
OIDC_REDIRECT_URI = os.getenv('OIDC_REDIRECT_URI', 'https://poc-tsdportal.it.slb.ru/auth/callback')

# URL фронтенда — backend редиректит сюда после успешного login/logout
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://poc-tsdportal.it.slb.ru')

# Scope для ADFS: allatclaims даёт Name + Family name; openid profile email — только email+alias
OIDC_RP_SCOPES = os.getenv('OIDC_SCOPES', 'allatclaims')
OIDC_USE_NONCE = False  # Не используется для базового ADFS flow
OIDC_RP_SIGN_ALGO = 'RS256'
OIDC_STORE_ACCESS_TOKEN = True
OIDC_STORE_ID_TOKEN = True
OIDC_RP_AUTHN_REQUEST_PARAMS = {
    'prompt': 'login',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # mozilla_django_oidc.middleware.SessionRefresh отключен:
    # модель Users не совместима с AbstractUser который он ожидает
]

ROOT_URLCONF = 'tsdp_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'users/templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tsdp_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': os.getenv('DB_NAME', 'tsddb'),
         'USER': os.getenv('DB_USER', 'tsddb'),
         'PASSWORD': os.getenv('DB_PASSWORD', 'qwerty'),
         'HOST': os.getenv('DB_HOST', 'localhost'),
         'PORT': os.getenv('DB_PORT', '3306'),
     },
    'second_db': {  # alias для второй базы данных
        'ENGINE': 'django.db.backends.mysql',  # или другой движок
        'NAME': os.getenv('SEC_DB_NAME'),
        'USER': os.getenv('SEC_DB_USER'),
        'PASSWORD': os.getenv('SEC_DB_PASSWORD'),
        'HOST': os.getenv('SEC_DB_HOST'),
        'PORT': os.getenv('SEC_DB_PORT'),
    }
    # Example of a secondary database configuration
    #'default': {
    #  'ENGINE': 'django.db.backends.mysql',
    #  'NAME': 'tsddb',
    #  'USER': 'tsddb',
    #   'PASSWORD': 'qwerty',
    #   'HOST': 'localhost',
    #    'PORT': '3306',
   # }

}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

MANAGER_JOB_TITLES_PATTERNS = [
    r'^Manager$',
    r'.*Lead.*'
]

SWAGGER_SETTINGS = {
    'DEFAULT_AUTO_SCHEMA_CLASS': 'tsdp_backend.swagger_config.OIDCSwaggerSchema',
    'USE_SESSION_AUTH': True,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        },
        'OIDC': {
            'type': 'oauth2',
            'flow': 'implicit',
            'authorizationUrl': '/oidc/authenticate/',
            'scopes': {
                'openid': 'OpenID scope',
                'email': 'Email access',
                'profile': 'Profile access',
            }
        }
    },
    'LOGIN_URL': '/oidc/authenticate/',
    'LOGOUT_URL': '/oidc/logout/',
}
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

OIDC_STORE_ACCESS_TOKEN = True
OIDC_STORE_ID_TOKEN = True
OIDC_STORE_USERINFO = True

# Для сохранения в базе данных сессий
SESSION_ENGINE = 'tsdp_backend.session_backend'  # таблица tsdb_sessions
SESSION_COOKIE_AGE = 43200  # 12 часов (как в примере ADFS)
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True  # Защита от XSS
SESSION_COOKIE_SAMESITE = 'Lax'  # Защита от CSRF, но разрешает GET редиректы с ADFS
# Статические настройки CSRF_TRUSTED_ORIGINS (для разработки)
# В продакшене используйте переменные окружения
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:3000',
    'http://localhost:3000',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://poc-tsdportal.it.slb.ru',
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter'
    ],
    'DATE_INPUT_FORMATS': ['%Y-%m-%d', '%d.%m.%Y'],
    'TIME_INPUT_FORMATS': ['%H:%M', '%H:%M:%S'],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.oidc_authentication.OIDCSessionAuthentication',  # OIDC session — единственный backend
        'rest_framework.authentication.BasicAuthentication',    # для Django admin
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}
AUTH_USER_MODEL = 'users.Users'

AUTHENTICATION_BACKENDS = [
    'users.backends.UsersAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# LDAP / Active Directory settings
LDAP_SERVER = os.getenv('LDAP_SERVER', 'ru0222dom02.slb.ru')
LDAP_PORT = int(os.getenv('LDAP_PORT', '636'))
LDAP_DOMAIN = os.getenv('LDAP_DOMAIN', 'slb.ru')
LDAP_VERIFY_TLS = os.getenv('LDAP_VERIFY_TLS', 'False') == 'True'

# SameSite для session_token cookie.
# Lax — production (same-site). None — разработка с фронтом на другом хосте (localhost:4200).
# SameSite=None требует Secure=True (уже выставлен).
COOKIE_SAMESITE = os.getenv('COOKIE_SAMESITE', 'Lax')

# CORS settings
# Для разработки по умолчанию разрешаем все источники
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL', 'True') == 'True'

# Если нужны конкретные источники, можно указать их через переменную окружения
# Они будут добавлены к базовым настройкам
_cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS')
if _cors_origins_env:
    additional_origins = _cors_origins_env.split(',')
    CORS_ALLOWED_ORIGINS = list(set(CSRF_TRUSTED_ORIGINS + additional_origins))

CORS_ALLOW_CREDENTIALS = True

# CSRF settings - динамические настройки дополняют статические
_csrf_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS')
if _csrf_origins_env:
    additional_csrf = _csrf_origins_env.split(',')
    CSRF_TRUSTED_ORIGINS = list(set(CSRF_TRUSTED_ORIGINS + additional_csrf))

# Reverse proxy settings
# Если используется HTTPS через reverse proxy (например, Apache/Nginx с SSL)
if os.getenv('USE_HTTPS_PROXY', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Использовать заголовки X-Forwarded-Host и X-Forwarded-Port
# По умолчанию включено для production (DEBUG=False)
USE_X_FORWARDED_HOST = os.getenv('USE_X_FORWARDED_HOST', str(not DEBUG)) == 'True'
USE_X_FORWARDED_PORT = os.getenv('USE_X_FORWARDED_PORT', str(not DEBUG)) == 'True'

SPECTACULAR_SETTINGS = {
    'TITLE': 'TSD Backend API',
    'DESCRIPTION': '''API documentation for the TSD Backend.''',
    'VERSION': '0.0.1',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/api/[a-z]+',
    'TAGS': [
        {'name': 'auth', 'description': 'Аутентификация: проверка сессии (/auth/me/)'},
        {'name': 'shifts', 'description': 'Shifts endpoints'},
        {'name': 'shift-templates', 'description': 'Shift templates endpoints'},
        {'name': 'users', 'description': 'Users endpoints'},
        {'name': 'shift-types', 'description': 'Shift types endpoints'},
        {'name': 'calendar-anomalies', 'description': 'Calendar anomalies endpoints'},
        {'name': 'calendar-anomaly-types', 'description': 'Anomaly types endpoints'},
        {'name': 'desks', 'description': 'Desks endpoints'},
        {'name': 'teams', 'description': 'Teams endpoints'},
        {'name': 'shift-patterns', 'description': 'Shift patterns endpoints'},
        {'name': 'schedule', 'description': 'Monthly schedule endpoints'},
    ],
    'SECURITY': [{'cookieAuth': []}],
    'PREPROCESSING_HOOKS': [],
    'POSTPROCESSING_HOOKS': [],
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'displayRequestDuration': True,
        'docExpansion': 'none',
        'filter': True,
        'showExtensions': False,
        'showCommonExtensions': True,
    },
    'REDOC_UI_SETTINGS': {
        'expandResponses': '200,201',
        'hideDownloadButton': False,
        'pathInMiddlePanel': True,
    },
    'ENUM_NAME_OVERRIDES': {},
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_COERCE_PATH_PK': True,
}

REDOC_SETTINGS = {
    'SPEC_URL': ('schema-json', {'format': '.json'}),
}